name: Orm build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - uses: actions/checkout@v4
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm run build
